version: '3'

services:
  emqx-broker:
    image: emqx:5.3.0
    environment:
    - "EMQX_NAME=emqx-broker"
    - "EMQX_HOST=node1-broker.emqx.io"
    - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
    - "EMQX_CLUSTER__STATIC__SEEDS=[emqx-broker@node1-broker.emqx.io]"
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    networks:
      my-bridge-network:
        aliases:
          - node1-broker.emqx.io
    ports:
      - 1884:1883
      - 8085:8083
      - 8086:8084
      - 8884:8883
      - 18084:18083

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: timescaledb
      POSTGRES_USER: adnim
      POSTGRES_PASSWORD: adnim
    volumes:
      - ./src/main/resources/schemas.sql:/docker-entrypoint-initdb.d/schemas.sql
    networks:
      my-bridge-network:
        aliases:
          - timescaledb
    restart: always

networks:
  my-bridge-network:
    driver: bridge
    external: true
